# LEGACY: Compose fragments are not kept in sync with the deploy monolithic compose.
# Deploy uses deploy-assets/docker-compose.yml by default.

# Description: Build own image of Postgres with AMQP support for release

services:
  db:
    build:
      context: build/postgres
      args:
        - POSTGRES_VERSION=${POSTGRES_VERSION:-16}
