# LEGACY: Compose fragments are not kept in sync with the deploy monolithic compose.
# Deploy uses deploy-assets/docker-compose.yml by default.

# Description: Build own image of MusicBrainz Server for release

services:
  musicbrainz:
    build:
      context: build/musicbrainz
      args:
        - POSTGRES_VERSION=${POSTGRES_VERSION:-16}
